# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('edad', models.CharField(blank=True, max_length=140, null=True)),
                ('displayName', models.CharField(blank=True, max_length=140, null=True)),
                ('photoURL', models.CharField(blank=True, max_length=140, null=True)),
                ('ocupacion', models.CharField(blank=True, choices=[('ciudadano', 'Ciudadano'), ('estudiante', 'Estudiante'), ('empresario', 'Empresario'), ('docente', 'Docente')], default='ciudadano', max_length=140, null=True)),
                ('telefono', models.CharField(blank=True, max_length=140, null=True)),
                ('udi', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
    ]
