# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
