# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161009_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='titulo',
            new_name='title',
        ),
    ]
