# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20161009_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(default='null', related_name='projects', to='projects.Category'),
        ),
    ]
