# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20161009_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Category'),
        ),
    ]
