# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20161009_1004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('title', 'id')]),
        ),
    ]
