# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20161014_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
