# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
