# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
