# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20161015_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='laRef',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
