# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='projects/%Y/%m/%d/archivos'),
        ),
    ]
