# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20161019_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alcance',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
