# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20161023_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
