# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20161023_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='foro',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
