# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_foro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='indicador',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
