# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_justificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificacion',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='justi_eje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='justi_indicador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Justificacion',
        ),
    ]
