# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_project_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
