# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20161031_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conclusiones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
