# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_project_conclusiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('foro', models.CharField(choices=[('Tula de Allende', 'Tula de Allende'), ('Tulancingo', 'Tulancingo'), ('Huejutla', 'Huejutla'), ('Ixmiquilpan', 'Ixmiquilpan'), ('Pachuca', 'Pachuca'), ('Otro', 'Otro')], max_length=140)),
                ('otro', models.CharField(blank=True, max_length=140, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
