# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='validado',
            field=models.CharField(choices=[('si', 'SI'), ('no', 'NO'), ('und', 'und')], default='und', max_length=10),
        ),
    ]
