# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_project_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='edad',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
