# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_project_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('edad', models.CharField(blank=True, max_length=140, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo', models.CharField(blank=True, max_length=140, null=True)),
                ('problematica', models.CharField(blank=True, max_length=140, null=True)),
                ('email', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
    ]
