# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20161009_1454'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ciudadano', 'Ciudadano'), ('estudiante', 'Estudiante'), ('empresario', 'Empresario'), ('docente', 'Docente')], default='ciudadano', max_length=140, null=True),
        ),
    ]
