# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20161009_1454'),
        ('accounts', '0002_auto_20161009_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
