# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161009_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='edad',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('ciudadano', 'Ciudadano'), ('estudiante', 'Estudiante'), ('empresario', 'Empresario'), ('docente', 'Docente')], default='ciudadano', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='udi',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
